snyk-labs/snyk-request-manager

README.md

docs: Update README with right client name

---

README.md
src/lib/request/request.ts
src/lib/request/requestManager.ts
test/lib/request/request.test.ts
test/lib/requestManager/normal-flows.test.ts
test/lib/requestManager/rate-limits.test.ts

Release changes
_Instructions on how to run this locally, background context, what to review, questions…_
- [Jira ticket SC-0000](https://snyksec.atlassian.net/browse/SC-0000)
_Visuals that may help the reviewer_

Release changes

---

src/lib/request/request.ts

had the UA from snyk-prevent by accident...

fix: update user-agent string for snyk-request-manager

---

src/lib/request/request.ts
src/lib/request/requestManager.ts

Customizes the snyk-request-manager User Agent based on whatever is using it.

feat: Get top parent name and customize UA

---

src/lib/customErrors/requestManagerErrors.ts
src/lib/error.ts

Add an extra debug when an API error occurs.

feat: debug for errors from API

---

.gitignore
.npmrc
package.json

feat: bump dependencies to reduce vulnerabilities

---

README.md
package.json
src/lib/examples.ts

chore: rm snyk dev dep

---

README.md

fix: update readme and force release

---

README.md
package.json

force new version

---

package.json

_Explain why this PR exists_
Updating the snyk-config package
- [Jira ticket TECHSERV-1819](https://snyksec.atlassian.net/browse/TECHSERV-1819)

feat: update snyk config package

---

package.json

Updates the snyk-config package

update the snyk config package

---

package.json

Reverts snyk-tech-services/snyk-request-manager#59

Revert "update the snyk config package"

---

src/lib/request/requestManager.ts

when generating the rest api url, replace app. by api. from the url if present.
For tests purposes.
_Instructions on how to run this locally, background context, what to review, questions…_
- [Jira ticket SC-0000](https://snyksec.atlassian.net/browse/SC-0000)
_Visuals that may help the reviewer_

fix: check replace app. by api. from url

---

src/lib/request/requestManager.ts

fix: do not retry 404s

---

package.json
src/lib/request/request.ts

- upgrade axios
- enable timeout of 5 mins to handle hanging API requests

feat: upgrade axios to 0.27.2 & enable timeouts

---

README.md

Mark repo as actively maintained

chore: mark as maintained

---

package.json
src/lib/request/request.ts
test/lib/request/rest-request.test.ts

Send expected REST API headers on requests with body like POST & PATCH

fix: send vnd.api+json for rest API calls with body

---

jest.config.js
package.json
tsconfig.json

Vulnerabilities exist in the version of the Axios library in use, this PR updates to a fixed version   
- [SNYK-JS-AXIOS-6032459](https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459)
- [SNYK-JS-AXIOS-6144788](https://security.snyk.io/vuln/SNYK-JS-AXIOS-6144788)
A couple minor additional tweaks were needed due to major version upgrade.
- [Jira ticket IM-55](https://snyksec.atlassian.net/browse/IM-55)

fix: update axios version to fix vulnerability

---

README.md
package.json

Updating vulnerable Axios version.
_Instructions on how to run this locally, background context, what to review, questions…_
- [Jira ticket SC-0000](https://snyksec.atlassian.net/browse/SC-0000)
_Visuals that may help the reviewer_

fix: bump axios lib to 1.7.4

---

README.md
package.json

Updates repository URL to new `snyk-labs` location. Required for semantic release.
_Instructions on how to run this locally, background context, what to review, questions…_
- [Jira ticket SC-0000](https://snyksec.atlassian.net/browse/SC-0000)
_Visuals that may help the reviewer_

fix: update repository URL
